name: hs-qr-code-show
version: '1.0.0'
slug: hs_qr_code
description: This addon provides a server runnning qrcode.show to create and display qrCodes on request.
url: "https://github.com/Hypercookie/hs-qrcode.show"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  80/tcp: 9999
